"""empty message

Revision ID: 956accc816d8
Revises: 
Create Date: 2024-02-23 01:06:17.561452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956accc816d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
